# Generated by Django 2.1 on 2018-08-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180815_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='/media/profile_image/def_image.png', upload_to='profile_image/'),
        ),
    ]
