# Generated by Django 2.1 on 2018-08-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180815_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_food',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
