# Generated by Django 2.1 on 2018-11-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20180823_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='media/profile_image/def_image.png', upload_to='media/profile_image/'),
        ),
    ]
