# Generated by Django 2.1 on 2018-08-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directmessage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='read',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='sent',
            field=models.DateTimeField(null=True),
        ),
    ]
