# Generated by Django 2.1 on 2018-08-22 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directmessage', '0002_auto_20180821_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_message', to='directmessage.DirectMessage'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='read',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
