# Generated by Django 2.1 on 2018-08-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directmessage', '0003_auto_20180822_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
