# Generated by Django 2.1 on 2018-08-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20180821_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='my_answer_importance',
            field=models.CharField(choices=[('Mandatory', 'Mandatory'), ('Very Important', 'Very Important'), ('Somewhat Important', 'Somewhat Important'), ('Not Important', 'Not Important')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='their_importance',
            field=models.CharField(choices=[('Mandatory', 'Mandatory'), ('Very Important', 'Very Important'), ('Somewhat Important', 'Somewhat Important'), ('Not Important', 'Not Important')], max_length=50),
        ),
    ]
