# Generated by Django 2.1 on 2018-09-16 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_userreportquestions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreportquestions',
            old_name='report_question',
            new_name='report_questions',
        ),
    ]
