# Generated by Django 2.1 on 2018-09-16 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20180916_1312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserReportQuestions',
            new_name='UserReportQuestion',
        ),
    ]
