# Generated by Django 2.1 on 2018-09-16 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20180916_1313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReportQuestion',
        ),
    ]
