# Generated by Django 2.1 on 2018-09-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_delete_userreportquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreport',
            old_name='sender',
            new_name='reporter',
        ),
        migrations.AlterField(
            model_name='userreport',
            name='report_category',
            field=models.CharField(choices=[('This person is annoying me', 'This person is annoying me'), ('They are pretending to be me or someone i know', 'They are pretending to be me or someone i know'), ('They are sharing inappropriate or offensive message', 'They are sharing inappropriate or offensive message'), ('This is a fake account', 'This is a fake account'), ('This profile represents a business or organization', 'This profile represents a business or organization'), ('They are using a different name than they use in everday life', 'They are using a different name than they use in everday life'), ('other', 'other')], max_length=50),
        ),
    ]
