# Generated by Django 2.1 on 2018-09-16 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20180916_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreport',
            old_name='detailed_reason',
            new_name='report_url',
        ),
    ]
