# Generated by Django 2.1 on 2018-09-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20180916_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='report_category',
            field=models.CharField(choices=[('This person is annoying me', 'This person is annoying me'), ('They are pretending to be me or someone i know', 'They are pretending to be me or someone i know'), ('They are sharing inappropriate or offensive message', 'They are sharing inappropriate or offensive message'), ('This is a fake account', 'This is a fake account'), ('This profile represents a business or organization', 'This profile represents a business or organization'), ('They are using a different name than they use in everday life', 'They are using a different name than they use in everday life'), ('other', 'other')], max_length=100),
        ),
    ]
